[package]
name = "Encryfer-X"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
chacha20poly1305 = "0.10.1"
cipher = "0.4.4"
ctr = "0.9.2"
dirs = "5.0.1"
hex = "0.4.3"
raw-cpuid = "11.1.0"
reqwest = {version = "0.12.7", features = ["blocking"]}
winapi = { version = "0.3.9", features = ["winuser","setupapi","dbghelp","wlanapi","winnls","wincon","fileapi","sysinfoapi", "fibersapi","debugapi","winerror", "wininet" , "winhttp" ,"synchapi","securitybaseapi","wincrypt","psapi", "tlhelp32", "heapapi","shellapi", "memoryapi", "processthreadsapi", "errhandlingapi", "winbase", "handleapi", "synchapi"] }
